### ISSUE TITLE
Expected string passed to parameter 'tag' of op 'ImageSummary', got 'input_image_1' of type 'str' instead.

### ISSUE THREAD

**Issue by cena001plus** [shekkizh/FCN.tensorflow#110]
Use the `axis` argument instead
Traceback (most recent call last):
  File "C:\Tools\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 511, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "C:\Tools\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1175, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Tools\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\constant_op.py", line 304, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\Tools\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\constant_op.py", line 245, in constant
    allow_broadcast=True)
  File "C:\Tools\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\constant_op.py", line 283, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "C:\Tools\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 501, in make_tensor_proto
    (dtype, nparray.dtype, values))
TypeError: Incompatible types: <dtype: 'string'> vs. object. Value is input_image_1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/sunvalley/myRepositories/FCN/FCN.tensorflow/FCN.py", line 231, in <module>
    tf.app.run()
  File "C:\Tools\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "D:/sunvalley/myRepositories/FCN/FCN.tensorflow/FCN.py", line 150, in main
    tf.summary.image("input_image", image, max_outputs=2)
  File "C:\Tools\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\summary\summary.py", line 136, in image
    tag=tag, tensor=tensor, max_images=max_outputs, name=scope)
  File "C:\Tools\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_logging_ops.py", line 481, in image_summary
    bad_color=bad_color, name=name)
  File "C:\Tools\Anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 520, in _apply_op_helper
    repr(values), type(values).__name__))
TypeError: Expected string passed to parameter 'tag' of op 'ImageSummary', got 'input_image_1' of type 'str' instead.

**Comment by cena001plus** [comment]
#tf.summary.
solve
