### ISSUE TITLE
KeyError: 'normalization'

### ISSUE THREAD

**Issue by sixisir** [shekkizh/FCN.tensorflow#116]
when I run the FCN.py, appearing  the error .

Traceback (most recent call last):
  File "/home/yons/PycharmProjects/untitled1/FCN.tensorflow-master/FCN.py", line 235, in <module>
    tf.app.run()
  File "/home/yons/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/yons/PycharmProjects/untitled1/FCN.tensorflow-master/FCN.py", line 153, in main
    pred_annotation, logits = inference(image, keep_probability)
  File "/home/yons/PycharmProjects/untitled1/FCN.tensorflow-master/FCN.py", line 79, in inference
    mean = model_data['normalization'][0][0][0]
KeyError: 'normalization'

**Comment by qinyifang** [comment]
have U resolve it?
