### ISSUE TITLE
errors with loss

### ISSUE THREAD

**Issue by jiao0805** [shekkizh/FCN.tensorflow#12]
I use tensorflow 1.0 gpu on windows and I got error:

Traceback (most recent call last):
  File "FCN.py", line 221, in <module>
    tf.app.run()
  File "C:\Users\SEELE\AppData\Local\Programs\Python\Python35\lib\site-packages\
tensorflow\python\platform\app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "FCN.py", line 152, in main
    loss = tf.reduce_mean((tf.nn.sparse_softmax_cross_entropy_with_logits(logits
,tf.squeeze(annotation, squeeze_dims=[3]),name="entropy")))
  File "C:\Users\SEELE\AppData\Local\Programs\Python\Python35\lib\site-packages\
tensorflow\python\ops\nn_ops.py", line 1684, in sparse_softmax_cross_entropy_wit
h_logits
    labels, logits)
  File "C:\Users\SEELE\AppData\Local\Programs\Python\Python35\lib\site-packages\
tensorflow\python\ops\nn_ops.py", line 1533, in _ensure_xent_args
    "named arguments (labels=..., logits=..., ...)" % name)
ValueError: Only call `sparse_softmax_cross_entropy_with_logits` with named argu
ments (labels=..., logits=..., ...)

How can I solve it?

**Comment by shekkizh** [comment]
The solution is suggested under Issue #9 
Thanks to @jiao0805 and @FKNoble.
