### ISSUE TITLE
ValueError: Unknown mat file type, version 110, 116

### ISSUE THREAD

**Issue by varungupta31** [shekkizh/FCN.tensorflow#128]
I'm using the following versions:

```
numpy                     1.16.6
python                    2.7.18
scipy                     1.2.1
tensorflow                0.12.0
```
I'm getting the following error upon running `FCN.py`

```
setting up vgg initialized conv layers ...
Traceback (most recent call last):
  File "FCN.py", line 230, in <module>
    tf.app.run()
  File "/home2/varungupta/anaconda3/envs/fcn/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "FCN.py", line 148, in main
    pred_annotation, logits = inference(image, keep_probability)
  File "FCN.py", line 73, in inference
    model_data = utils.get_model_data(FLAGS.model_dir, MODEL_URL)
  File "/home2/varungupta/FCN.tensorflow/TensorflowUtils.py", line 19, in get_model_data
    data = scipy.io.loadmat(filepath)
  File "/home2/varungupta/anaconda3/envs/fcn/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 207, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/home2/varungupta/anaconda3/envs/fcn/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 63, in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
  File "/home2/varungupta/anaconda3/envs/fcn/lib/python2.7/site-packages/scipy/io/matlab/miobase.py", line 241, in get_matfile_version
    raise ValueError('Unknown mat file type, version %s, %s' % ret)
ValueError: Unknown mat file type, version 110, 116

```

I have structured my directory in the following manner:

```
.
├── BatchDatsetReader.py
├── BatchDatsetReader.pyc
├── Data_zoo
│   └── MIT_SceneParsing
│       └── ADEChallengeData2016
│           ├── annotations
│           │   ├── training
│           │   │   
│           ├── images
│           │   ├── training
│           │   └── validation
│           ├── objectInfo150.txt
│           └── sceneCategories.txt
├── FCN.py
├── __init__.py
├── LICENSE
├── logs
│   └── images
├── Model_zoo
│   └── imagenet-vgg-verydeep-19.mat
├── README.md
├── read_MITSceneParsingData.py
├── read_MITSceneParsingData.pyc
├── TensorflowUtils.py
└── TensorflowUtils.pyc
```
How can I resolve the error?
@shekkizh @lababidi

**Comment by varungupta31** [comment]
Downgrading the scipy version solved it for me.

**Comment by WANGZEQI123** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
