### ISSUE TITLE
How can i solve these problems?

### ISSUE THREAD

**Issue by eserercanakin** [shekkizh/FCN.tensorflow#13]
runfile('C:/Users/PROCOMP-9/Desktop/FCN.tensorflow-master/FCN.tensorflow-master/FCN.py', wdir='C:/Users/PROCOMP-9/Desktop/FCN.tensorflow-master/FCN.tensorflow-master')
setting up vgg initialized conv layers ...
Setting up summary op...
Setting up image reader...
Found pickle file!
0
0
Setting up dataset reader
Initializing Batch Dataset Reader...
{'resize': True, 'resize_size': 224}
(0,)
(0,)
Initializing Batch Dataset Reader...
{'resize': True, 'resize_size': 224}
(0,)
(0,)
Setting up Saver...
****************** Epochs completed: 1******************
```
Traceback (most recent call last):

  File "<ipython-input-1-6062f5716837>", line 1, in <module>
    runfile('C:/Users/PROCOMP-9/Desktop/FCN.tensorflow-master/FCN.tensorflow-master/FCN.py', wdir='C:/Users/PROCOMP-9/Desktop/FCN.tensorflow-master/FCN.tensorflow-master')

  File "C:\Users\PROCOMP-9\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Users\PROCOMP-9\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/PROCOMP-9/Desktop/FCN.tensorflow-master/FCN.tensorflow-master/FCN.py", line 223, in <module>
    tf.app.run()

  File "C:\Users\PROCOMP-9\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))

  File "C:/Users/PROCOMP-9/Desktop/FCN.tensorflow-master/FCN.tensorflow-master/FCN.py", line 194, in main
    sess.run(train_op, feed_dict=feed_dict)

  File "C:\Users\PROCOMP-9\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 766, in run
    run_metadata_ptr)

  File "C:\Users\PROCOMP-9\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 943, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))

ValueError: Cannot feed value of shape (0,) for Tensor 'input_image:0', which has shape '(?, 224, 224, 3)'
```

**Comment by jiao0805** [comment]
Did you run on windows?

The output of your pickle file is 
0
0

which means that  when you read image lists , your system found nothing
Please check the os.path.splitext() function in your read_MITSceneParsingData.py file.
If you are windows it should be "\\"instead of "/" 

please reference to issue 9

**Comment by eserercanakin** [comment]
Yes I run on windows10. I think, when I use "\" , code working properly.
Maybe the problem is another thing.
[image: Satır içi resim 1]

2017-03-16 8:09 GMT+03:00 小狮子 <notifications@github.com>:

**Comment by jiao0805** [comment]
Sorry,
USE \\\ please not \\
Your pickle file is 
0
0
That means your computer find no directory.

**Comment by shekkizh** [comment]
@eserercanakin Did the solution posted above solve the problem? Please close issue if it did.

Thanks.

**Comment by shekkizh** [comment]
Closing due to inactivity.

**Comment by chankeh** [comment]
I  have  solved some problems both in ubuntu and Windows10 , and now the code can run very well.
some tips you should know.
1.unzip the dataset and download the mat file
2.you should know the difference between linux and window, such as os.path.splitext() function,you must   replace '/' with '\\'(use two'\\',caution) in windows.
3.use a computer which equiped with gpu. 
I think , if you solved above problems , the code will be runed well.
 
----------------------------------------------------------------------------------------
   2017/05/11   in ShenYang,China,Northeastern University.

**Comment by Patickk** [comment]
@chankeh 
hi chankeh,
Thank you for your suggesions, but i still have the same question:
**ValueError: Cannot feed value of shape (0,) for Tensor 'input_image:0', which has shape '(?, 224, 224, 3)'**

i have tried both, but didn't work:
1.SceneParsing_folder = os.path.splitext(DATA_URL.split("\\")[-1])[0] 
   filename = os.path.splitext(f.split("\\")[-1])[0]
2.SceneParsing_folder = os.path.splitext(DATA_URL.split("/")[-1])[0] 
   filename = os.path.splitext(f.split("\\")[-1])[0]

I am a learner,my computer is windows tf0.12 gpu1060, could you help me?
best regards

**Comment by chankeh** [comment]
i also used tf0.12rc ,but  some problems you just raised doesn't occur.
please check whether your path is right.
and my path is like this,
        FCN.tensorflow-master\Data_zoo\MIT_SceneParsing
        FCN.tensorflow-master\Model_zoo
i think  maybe  it is the path error.

**Comment by chankeh** [comment]
@Patickk 
i also used tf0.12rc ,but some problems you just raised doesn't occur.
please check whether your path is right.
and my path is like this,
FCN.tensorflow-master\Data_zoo\MIT_SceneParsing
FCN.tensorflow-master\Model_zoo
i think maybe it is the path error.

**Comment by Patickk** [comment]
@chankeh 
thanks bro,and I have sove the problem: 
I deleted the data, run the code ,and it worked!.....lol, may be there is a bug on my old data
so ,i have a new problem:

    training_records = result['training']
TypeError: 'NoneType' object is not subscriptable

i didn't find the answer to solve this ,and there is no questions about this, do you think it's also a bug? 
best regards

**Comment by chankeh** [comment]
@Patickk 
did you download this data ? ----> MIT_SceneParsing
this  is the trainning and test dataset , and you should put it in the folder, Data_zoo,which should locate in the root path,the same path with your python file.(Data_zoo' path is the same as python file )  
and  you should know that  the difference between linux and wndows(if you are using linux,you should use '/' ,while if you are using windows ,you shoule use '\\'(two '\\',because it is  transferred by the system here.))
the problems you just raised is still the path problem

**Comment by songwaimai** [comment]
hello~hi~
some questions i can't find out the reason. First I run the code with cpu, does it allowed? and i have replaced '/' with '\\' , the dataset is under the right path. it still the same error:
![qq 20170817110125](https://user-images.githubusercontent.com/28387961/29394223-94d6d990-833b-11e7-82d9-95f4676e7b0a.png)

**Comment by Wuranker** [comment]
Before generating "MITSceneParsing.pickle", I use '\\\\' instead of  '/' (line 54 in "read_MITSceneParsingData.py"), and solve the problem.

**Comment by wxwhu** [comment]
@chankeh 
hello
Sorry to bother you,I use  '\\' instead of '/' .But it doesn't work.I use WIN10 .It gives the same error.Do you know the reason?
Thank you very much!
![qq 20171218110247](https://user-images.githubusercontent.com/32167040/34088250-1b21fc52-e3e3-11e7-8730-adde93c68a7c.png)
![qq 20171218110309](https://user-images.githubusercontent.com/32167040/34088251-1b6150a0-e3e3-11e7-9398-702edfa4f247.png)

**Comment by chankeh** [comment]
@wxwhu 
hello ， you shouldn't change  other .py files but  FCN.py 

in this line ,you must use ' SceneParsing_folder = os.path.splitext(DATA_URL.split("/")[-1])[0]'

**Comment by chankeh** [comment]
@wxwhu 
it seems that your data'path is wrong.
structure like this,
![tf](https://user-images.githubusercontent.com/23022486/34100712-521f3fa4-e41e-11e7-9f06-58f6b8861707.jpg)

**Comment by wxwhu** [comment]
@chankeh 
this is my path.I don't know where it goes wrong.
![default](https://user-images.githubusercontent.com/32167040/34135702-456f0f4e-e49d-11e7-8b32-4c787315028e.png)
![1](https://user-images.githubusercontent.com/32167040/34135704-45a5c57a-e49d-11e7-933b-9331fb341605.png)
![2](https://user-images.githubusercontent.com/32167040/34135705-45dd43ec-e49d-11e7-8394-589d7ad149e2.png)

**Comment by chankeh** [comment]
@wxwhu
path like this，
![qq 20171219092625](https://user-images.githubusercontent.com/23022486/34136016-d147dd88-e49e-11e7-98b8-ef46c2ad46c2.jpg)

**Comment by chankeh** [comment]
as the following，
`FLAGS = tf.flags.FLAGS
tf.flags.DEFINE_integer("batch_size", "2", "batch size for training")
tf.flags.DEFINE_string("logs_dir", "logs\\", "path to logs directory")# 记得要把'/'改成'\\'
tf.flags.DEFINE_string("data_dir", "Data_zoo\\MIT_SceneParsing\\", "path to dataset")# 记得要把'/'改成'\\'
tf.flags.DEFINE_float("learning_rate", "1e-4", "Learning rate for Adam Optimizer")# 记得要把'/'改成'\\'
tf.flags.DEFINE_string("model_dir", "Model_zoo\\", "Path to vgg model mat")# 记得要把'/'改成'\\'
tf.flags.DEFINE_bool('debug', "False", "Debug mode: True/ False")
tf.flags.DEFINE_string('mode', "train", "Mode train/ test/ visualize")`

**Comment by chankeh** [comment]
@wxwhu 
as the following，
![qq 20171219093120](https://user-images.githubusercontent.com/23022486/34136172-99eaa9f0-e49f-11e7-91c7-0a3beb99ff77.jpg)

**Comment by wxwhu** [comment]
@chankeh thaks,but It works bad,but it gives the same error.
![4](https://user-images.githubusercontent.com/32167040/34136367-4534b6de-e4a0-11e7-9702-fab9c3ad1c9f.png)
![5](https://user-images.githubusercontent.com/32167040/34136369-456aca3a-e4a0-11e7-9798-72965d1226ef.png)
![6](https://user-images.githubusercontent.com/32167040/34136370-45a0ebe2-e4a0-11e7-8864-b0809deb6a5b.png)

**Comment by wxwhu** [comment]
@chankeh 
hello,I delete 'not' and it find the file like this .but does it mean working well？
![7](https://user-images.githubusercontent.com/32167040/34136890-e18898fa-e4a2-11e7-9304-38ae21f267d0.png)
![8](https://user-images.githubusercontent.com/32167040/34136891-e1be9892-e4a2-11e7-80f6-1e2fe0cd9ebd.png)

**Comment by chankeh** [comment]
@wxwhu 
yes，it means  right

**Comment by MarkYangjiayi** [comment]
@Patickk Hello, i ran into the same problem you do about the TypeError: 'NoneType' object is not subscriptable.
Wonder if you ever fixed this problem,tks.

**Comment by xcnie** [comment]
> @chankeh
> hello,I delete 'not' and it find the file like this .but does it mean working well？
> ![7](https://user-images.githubusercontent.com/32167040/34136890-e18898fa-e4a2-11e7-9304-38ae21f267d0.png)
> ![8](https://user-images.githubusercontent.com/32167040/34136891-e1be9892-e4a2-11e7-80f6-1e2fe0cd9ebd.png)

your method is working. I think it is because we have run FCN.py. So there is a file "MITSceneParsing.pickle". If we delete it, we need not delete "not''

**Comment by luo-haoyu** [comment]
I had the same problem that 'ValueError: Cannot feed value of shape (0,).....'
Then I found the size of the file 'MITSceneParsing.pickle'  is just 1KB,which means maybe nothing in it.
When I delete it and run the code again, it work without the ValueError !

So I suppose that when you change '/' into '\' in windows, you should delete the MITSceneParsing.pickle generated before and run the code to regenerate it.

**Comment by varungupta31** [comment]
Hey, to anyone still subscribed to this thread, please help me out with my [issue#128](https://github.com/shekkizh/FCN.tensorflow/issues/128#issue-1143046092).

I'm getting a `ValueError: Unknown mat file type, version 110, 116`.
I have correctly structured my directory as suggested, and am on Ubuntu 20.04.

Any help is appreciated, thanks.

**Comment by WANGZEQI123** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
