### ISSUE TITLE
AttributeError: 'module' object has no attribute 'get_model_data'

### ISSUE THREAD

**Issue by Yaredoh** [shekkizh/FCN.tensorflow#20]
```
/usr/bin/python2.7 /home/yared/Desktop/Project/FCN.py
  setting up vgg initialized conv layers ...
     Traceback (most recent call last):
     File "/home/yared/Desktop/Project/FCN.py", line 225, in <module>
       tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/home/yared/Desktop/Project/FCN.py", line 150, in main
    pred_annotation, logits = inference(image, keep_probability)
  File "/home/yared/Desktop/Project/FCN.py", line 75, in inference
    model_data = utils.get_model_data(FLAGS.model_dir, MODEL_URL)
AttributeError: 'module' object has no attribute 'get_model_data'
```

**Comment by shekkizh** [comment]
Can you check if TensorflowUtils.py has the method in question? Maybe cloning the repository again solves the problem for you. This is not a problem with the code.
