### ISSUE TITLE
Windows GPU 0.12version issue

### ISSUE THREAD

**Issue by fanhualta** [shekkizh/FCN.tensorflow#55]
I used the version 0.12rc, but it occured like this：

Traceback (most recent call last):
Found pickle file!
File "E:/Python/FCN/FCN.py", line 224, in 
tf.app.run()
File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 43, in run
sys.exit(main(sys.argv[:1] + flags_passthrough))
File "E:/Python/FCN/FCN.py", line 168, in main
train_records, valid_records = scene_parsing.read_dataset(FLAGS.data_dir)
File "E:\Python\FCN\read_MITSceneParsingData.py", line 30, in read_dataset
training_records = result['training']
TypeError: 'NoneType' object is not subscriptable

how can i fixed this problem？
thanks.

**Comment by ZengDongDon** [comment]
In Windows, the os.path.splittext() should use "\ \", rather than '/'. Otherwise, the program can't find any files to pickle (and the MITSceneParsing.pickle file is empty), which in turn means 0 records are found and the feed dict instruction doesn't work. you want to find more ,please link:
https://github.com/shekkizh/FCN.tensorflow/issues/9
