### ISSUE TITLE
CUDA_ERROR_OUT_OF_MEMORY

### ISSUE THREAD

**Issue by amiltonwong** [shekkizh/FCN.tensorflow#6]
Hi, @shekkizh ,

I got the following error:

```
root@milton-OptiPlex-9010:/data/code/FCN.tensorflow# python FCN.py 
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so.7.5 locally
setting up vgg initialized conv layers ...
Setting up summary op...
Setting up image reader...
Found pickle file!
20210
2000
Setting up dataset reader
Initializing Batch Dataset Reader...
{'resize_size': 224, 'resize': True}
(20210, 224, 224, 3)
(20210, 224, 224, 1)
Initializing Batch Dataset Reader...
{'resize_size': 224, 'resize': True}
(2000, 224, 224, 3)
(2000, 224, 224, 1)
E tensorflow/core/common_runtime/direct_session.cc:135] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 18446744073709551615
Traceback (most recent call last):
  File "FCN.py", line 223, in <module>
    tf.app.run()
  File "/root/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "FCN.py", line 177, in main
    sess = tf.Session()
  File "/root/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1186, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/root/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 551, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/root/anaconda3/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/root/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.
```

Could you suggest me how to fix this error: "CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 18446744073709551615"

**Comment by amiltonwong** [comment]
How large of GPU are required to run "python FCN.py"?

**Comment by shekkizh** [comment]
@amiltonwong Sorry I couldn't comment on your issue sooner. I used a titanx which is a 12gb card. 
The total memory reported number doesn't really make sense to me - maybe nvidia forums could shed more light for you with this error.

**Comment by amiltonwong** [comment]
Hi, @shekkizh ,

Thanks for your reply. I finally figure it out. The reason is that the GPU is occupied by another tf process before. After I reboot the machine, the code works.

BTW, could you list the steps about how to obtain the figures in README.md: [fig1](https://github.com/shekkizh/FCN.tensorflow/blob/master/logs/images/sparse_entropy.png), [fig2](https://github.com/shekkizh/FCN.tensorflow/blob/master/logs/images/conv_1_1_gradient.png), etc during the training process?

THANKS!

**Comment by shekkizh** [comment]
Use the code within "visualize" in your training process to save segmentation results during training.

**Comment by shekkizh** [comment]
Sorry. I mistook the pictures for segmentation results. If you are just looking for the graph of loss function or weight distribution, use tensorboard. The code already dumps the necessary values in the logs folder.
