### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by MandyMo** [shekkizh/FCN.tensorflow#78]
Step: 5050, Train_loss:1.6929
****************** Epochs completed: 1******************
Traceback (most recent call last):
  File "FCN.py", line 223, in <module>
    tf.app.run()
  File "C:\Users\medusa\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "FCN.py", line 191, in main
    train_images, train_annotations = train_dataset_reader.next_batch(FLAGS.batch_size)tch(FLAGS.batch_size)
  File "D:\ML\FCN\FCN.tensorflow\BatchDatsetReader.py", line 72, in next_batch    self.images = self.images[perm]
MemoryError

i got this runtime error, anybody have meet the same runtime error?

**Comment by shekkizh** [comment]
Closing due to inactivity. Exhausted ram/ cache?!
