### ISSUE TITLE
wimdows

### ISSUE THREAD

**Issue by CCTV-lulu** [shekkizh/FCN.tensorflow#80]
Hi,
I use tensorflow 1.4 gpu on windows 10 , and I saw the issues you shared above.
I did all of them but I still got one error as follows:
Traceback (most recent call last):
  File "FCN.py", line 223, in <module>
    tf.app.run()
  File "C:\Users\mrrobot\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "FCN.py", line 148, in main
    pred_annotation, logits = inference(image, keep_probability)
  File "FCN.py", line 73, in inference
    model_data = utils.get_model_data(FLAGS.model_dir, MODEL_URL)
  File "C:\FCN.tensorflow\TensorflowUtils.py", line 19, in get_model_data
    data = scipy.io.loadmat(filepath)
  File "C:\Users\mrrobot\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\io\matlab\mio.py", line 142, in loadmat
    matfile_dict = MR.get_variables(variable_names)
  File "C:\Users\mrrobot\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\io\matlab\mio5.py", line 292, in get_variables
    res = self.read_var_array(hdr, process)
  File "C:\Users\mrrobot\AppData\Local\Programs\Python\Python36\lib\site-packages\scipy\io\matlab\mio5.py", line 252, in read_var_array
    return self._matrix_reader.array_from_header(header, process)
  File "mio5_utils.pyx", line 675, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 721, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 894, in scipy.io.matlab.mio5_utils.VarReader5.read_cells
  File "mio5_utils.pyx", line 673, in scipy.io.matlab.mio5_utils.VarReader5.read_mi_matrix
  File "mio5_utils.pyx", line 723, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 969, in scipy.io.matlab.mio5_utils.VarReader5.read_struct
  File "mio5_utils.pyx", line 673, in scipy.io.matlab.mio5_utils.VarReader5.read_mi_matrix
  File "mio5_utils.pyx", line 721, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 894, in scipy.io.matlab.mio5_utils.VarReader5.read_cells
  File "mio5_utils.pyx", line 673, in scipy.io.matlab.mio5_utils.VarReader5.read_mi_matrix
  File "mio5_utils.pyx", line 705, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 778, in scipy.io.matlab.mio5_utils.VarReader5.read_real_complex
  File "mio5_utils.pyx", line 450, in scipy.io.matlab.mio5_utils.VarReader5.read_numeric
  File "mio5_utils.pyx", line 355, in scipy.io.matlab.mio5_utils.VarReader5.read_element
  File "streams.pyx", line 94, in scipy.io.matlab.streams.GenericStream.read_string
  File "streams.pyx", line 81, in scipy.io.matlab.streams.GenericStream.read_into
OSError: could not read bytes
It seems that there is something wrong with my cost function.
Did you meet this error on win10?
Could you please kindly tell me how can I solve it?

**Comment by shekkizh** [comment]
Closing due to inactivity.  Seems more like a scipy mat read issue?!
